# First configuration
---
path: /bighello/:name
# port: 8080
# ca marche ça ? juste apres
urlParam:
    name: string
query:
  civ: string:mandatory
actions:
  - type: sql
    in: inMemory
    command: insert into tbl (nom, civ) values (?, ?);
    param:
      - name
      - civ
    save: tab
  - type: sql
    in: inMemory
    command: select nom, civ from tbl;
    save: tab
  #- sql: inMemory> load> select count(nom) nb from tbl where civ=?:civ;
  #- sql: inMemory> insert> insert into tbl (civ, cnt) values (?:civ, ?:nb);
response:
  # format: txt json yaml
  json:
    civ: :civ
    name: :name
    sqlresult: :tab
    data:
      - oui
      - non