# First configuration
---
path: /books/:id
method: DELETE
# port: 8080
urlParam:
    id: Integer[1-6]
actions:
  - type: sql
    in: postgres
    command: delete from book where id = ?;
    param:
      - id
    save: book
response:
  json:
    book: :book