# First configuration
---
path: /books
method: POST
# port: 8080
body:
    title: String[/[a-z]+/]
    author: String
actions:
  - type: sql
    in: postgres
    command: insert into book (title, author) values (?, ?);
    param:
      - title
      - author
    save: id
response:
  json:
    id: :id