# First configuration
---
path: /books
method: GET
# port: 8080
actions:
  - type: sql
    in: postgres
    command: select id, title, author from book;
    output:
          title: String
          author: String
          id: Integer
    save: bookList
response:
  json:
    collection: :bookList